# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/tekwizely/pre-commit-golang
    rev: v0.8.2
    hooks:
    -   id: go-test-repo-mod
    -   id: go-fmt
    -   id: golangci-lint-repo-mod
    -   id: go-vet-repo-mod
