services:
    app:
        build: ./
        environment:
            DATABASE_URL: "redis:6379"
            DATABASE_PASS: ""
            DATABASE_ID: "0"
            PORT: ":8080"
        ports:
            - "8080:8080"
        depends_on:
            - redis
    redis:
        image: redis:latest
